prepare fe workflow

diff --git a/.github/workflows/frontend-workflow.yml b/.github/workflows/frontend-workflow.yml
--- a/.github/workflows/frontend-workflow.yml
+++ b/.github/workflows/frontend-workflow.yml
@@ -10,10 +10,14 @@ on:
         required: false
         type: string
         default: 'false'
-      ros_distro:
-        required: true
+      run_tests:
+        required: false
         type: string
-        
+        default: 'true'
+      npm_version:
+        required: false
+        type: string
+        default: '16.x'
 
     secrets:
       auto_commit_user:
@@ -28,13 +32,11 @@ on:
         required: true
       nexus_publisher_password:
         required: true
-      aws_sqs_rosdep_access_key:
-        required: true
-      aws_sqs_rosdep_secret_access_key:
-        required: true
       gh_token:
         required: true
       sonar_token:
+        required: true
+      npm_token:
         required: true
 
 jobs:
@@ -47,31 +49,28 @@ jobs:
         username: ${{secrets.PORTUS_APP_USER}} 
         password: ${{secrets.PORTUS_APP_TOKEN}}
     env:
-      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
 
     steps:
     - name: Checkout    
       uses: actions/checkout@v2
       with:
-        token: ${{ secrets.NPM_TOKEN }}
         # Disabling shallow clone is recommended for improving relevancy of reporting
         fetch-depth: 0
         submodules: recursive
+        token: ${{ secrets.npm_token }}
 
     - name: Raise App version
       run: |
-        git config --global user.name '${{ secrets.RAISE_BOT_COMMIT_USER }}'
-        git config --global user.email '${{ secrets.RAISE_BOT_COMMIT_MAIL }}'
-        npm version prerelease -m "Automatic Bump of build version"
-        git pull
-        git add package.*
-        git push
+        git config --global user.name '${{ secrets.auto_commit_user }}'
+        git config --global user.email '${{ secrets.auto_commit_mail }}'
+        npm version patch --no-git-tag-version
 
 
     - name: Setup Github as proxy Registry 
       uses: actions/setup-node@v2
       with:
-        node-version: '16.x'
+        node-version: '${{ inputs.npm_version }}'
         registry-url: 'https://npm.pkg.github.com/mov-ai'
 
     - name: Find Package details
@@ -124,10 +123,9 @@ jobs:
         echo "Please check report here: https://sonarqube.aws.cloud.mov.ai/dashboard?id=${{ github.event.repository.name }}"
       id: sonar_links
 
-
-    # Skip tests for now
-    #- name: Run tests
-    #  run: npm run test
+    - name: Run tests
+      if: ${{ inputs.run_tests == 'true' }}
+      run: npm run test
 
     - name: Bump manifest.json metadata Version
       uses: deef0000dragon1/json-edit-action/@v1
@@ -143,6 +141,20 @@ jobs:
         mkdir artifacts && \
         cp ../*.deb artifacts
 
+    - name: Print generated packages
+      run: |
+        ls -la artifacts
+
+    - name: Publish npm
+      if: ${{ inputs.deploy == 'true' }}
+      run: npm publish
+
+    - name: Archive binary
+      if: ${{ inputs.deploy == 'true' }}
+      uses: actions/upload-artifact@v2
+      with:
+        name: packages
+        path: artifacts/*
 
 
   Publish:
@@ -158,7 +170,6 @@ jobs:
 
     steps:
     - name: Checkout    
-      if: ${{ inputs.deploy == 'true' }}
       uses: actions/checkout@v2
       with:
         # Disabling shallow clone is recommended for improving relevancy of reporting
@@ -166,36 +177,90 @@ jobs:
         submodules: recursive
         
     - name: Download a single artifact
-      if: ${{ inputs.deploy == 'true' }}
       uses: actions/download-artifact@v2
       with:
         name: packages
         path: artifacts
 
-    - name: Publish
-      run: npm publish
-
     - name: Publish to Nexus ppa-dev
+      shell: bash
       run: |
+          echo ${BASH_VERSION}
           NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
           NEXUS_REPO="ppa-dev"
-          FILE_LOCATION=$(find artifacts/*.deb)
-          curl -u "${{ secrets.NEXUS_PUBLISHER_USR }}:${{ secrets.NEXUS_PUBLISHER_PWD }}" \
-          -H "Content-Type: multipart/form-data" \
-          --data-binary "@$FILE_LOCATION" \
-          "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/"
-  
+
+          for file in artifacts/*.deb
+          do
+            RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+            -H "Content-Type: multipart/form-data" \
+            --data-binary "@$file" \
+            -w '%{http_code}' \
+            "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Retrying"
+            
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                -H "Content-Type: multipart/form-data" \
+                --data-binary "@$file" \
+                -w '%{http_code}' \
+                "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+            fi
+
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+            
+          done
+    
     - name: Publish to Nexus ppa-testing
+      shell: bash
       run: |
+          echo ${BASH_VERSION}
           NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
           NEXUS_REPO="ppa-testing"
-          FILE_LOCATION=$(find artifacts/*.deb)
-          curl -u "${{ secrets.NEXUS_PUBLISHER_USR }}:${{ secrets.NEXUS_PUBLISHER_PWD }}" \
-          -H "Content-Type: multipart/form-data" \
-          --data-binary "@$FILE_LOCATION" \
-          "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/"
 
-    - name: Create Github Release
+          for file in artifacts/*.deb
+          do
+            RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+            -H "Content-Type: multipart/form-data" \
+            --data-binary "@$file" \
+            -w '%{http_code}' \
+            "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Retrying"
+            
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                -H "Content-Type: multipart/form-data" \
+                --data-binary "@$file" \
+                -w '%{http_code}' \
+                "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+            fi
+
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+            
+          done
+
+    - name: Raise App version
+      id: raise
+      run: |
+        git config --global user.name '${{ secrets.auto_commit_user }}'
+        git config --global user.email '${{ secrets.auto_commit_mail }}'
+        npm version patch -m "Automatic Bump of build version" 
+        git add package.*
+        git push
+        commit_id=$(git log --format="%H" -n 1)
+        echo ::set-output name=commit_id::$VERSION  
+
+
+    - name: Grep manual release notes
       shell: bash
       run: |
         # contains more than one release ?
@@ -205,19 +270,18 @@ jobs:
         else
           body=$(cat CHANGELOG.md)
         fi
-        
-        title="Release of ${{ steps.vars.outputs.npm_pkg_version }}" 
-        
-        gh release create -p -t "$title" -n "$body" ${{ steps.vars.outputs.npm_pkg_version }}
 
-        # add all files in the artifacts folder
-        ls -la artifacts
-        find artifacts -type f -exec gh release upload ${{ steps.vars.outputs.npm_pkg_version }} {} \;
-        
-
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-     
+    - name: Create Github Release
+      uses: softprops/action-gh-release@v1
+      with:
+        name: "Release of ${{ steps.vars.outputs.npm_pkg_version }}"
+        body_path: CHANGELOG.md
+        tag_name: ${{ steps.vars.outputs.npm_pkg_version }}
+        target_commitish: ${{ steps.raise.outputs.commit_id }}
+        token: ${{ secrets.gh_token }}
+        prerelease: true
+        generate_release_notes: true
+        files: artifacts/*.deb
 
   Release:
     if: ${{ inputs.release == 'true' }}
