DP-1435 create v2.1

diff --git a/.github/workflows/integration-build-product-composite.yml b/.github/workflows/integration-build-product-composite.yml
--- a/.github/workflows/integration-build-product-composite.yml
+++ b/.github/workflows/integration-build-product-composite.yml
@@ -27,10 +27,16 @@ on:
         required: false
         type: boolean
         default: false
-      fleet_ips:
+      single_vm_fleet_ips:
         required: true
         type: string
-      fleet_number_members:
+      single_vm_fleet_number_members:
+        required: true
+        type: number
+      multi_vm_fleet_ips:
+        required: true
+        type: string
+      multi_vm_fleet_number_members:
         required: true
         type: number
       with_simulation:
@@ -1036,7 +1042,7 @@ jobs:
           docker image prune --all -f
         
 
-  Install-Heterogeneos-Fleet:
+  Install-Heterogeneos-Fleet-Single-VM:
     needs: [Build-Spawner]
     strategy:
       matrix:
@@ -1116,12 +1122,12 @@ jobs:
           terraform plan
           terraform apply -auto-approve
         env:
-          TF_VAR_number_agents: ${{ inputs.fleet_number_members }}
+          TF_VAR_number_agents: ${{ inputs.single_vm_fleet_number_members }}
           TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
           TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
           TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
           TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
-          TF_VAR_ip_list: ${{ inputs.fleet_ips }}
+          TF_VAR_ip_list: ${{ inputs.single_vm_fleet_ips }}
           TF_VAR_proxmox_host: "hel"
           TF_VAR_vm_gateway: "172.22.0.1"
           TF_VAR_ip_mask: 24
@@ -1185,7 +1191,7 @@ jobs:
           echo "${{ secrets.ssh_pem_fleet_aws_vm }}" > ~/.ssh/aws_slave.pem
           sudo chmod 600 ~/.ssh/aws_slave.pem
 
-          stripped_ips=$(echo ${{ inputs.fleet_ips }} | sed "s;\[;;g" | sed "s;];;g" | sed "s; ;;g")
+          stripped_ips=$(echo ${{ inputs.single_vm_fleet_ips }} | sed "s;\[;;g" | sed "s;];;g" | sed "s; ;;g")
           touch ~/.ssh/known_hosts
           sudo chmod 600 ~/.ssh/known_hosts
           IFS=',' read -r -a stripped_ips_arr <<< $stripped_ips
@@ -1323,12 +1329,12 @@ jobs:
         shell: bash
         run: terraform destroy -auto-approve
         env:
-          TF_VAR_number_agents: ${{ inputs.fleet_number_members }}
+          TF_VAR_number_agents: ${{ inputs.single_vm_fleet_number_members }}
           TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
           TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
           TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
           TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
-          TF_VAR_ip_list: ${{ inputs.fleet_ips }}
+          TF_VAR_ip_list: ${{ inputs.single_vm_fleet_ips }}
   
       - name: Stash project metadata
         if: always()
@@ -1364,9 +1370,337 @@ jobs:
           docker system prune -f
           docker image prune --all -f
 
+  Install-Heterogeneos-Fleet-Multi-VM:
+    needs: [Build-Spawner]
+    strategy:
+      matrix:
+        distro: ${{ fromJSON(inputs.ros_distro) }}
+    runs-on: integration-pipeline
+
+    steps:
+      - uses: rtCamp/action-cleanup@master
+
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Agent info
+        run: |
+          echo "public ip: $(curl ipinfo.io/ip)"
+          echo "private ip: $(hostname -I | awk '{print $1}')"
+
+      - name: unstash raised_meta
+        uses: actions/download-artifact@v3
+        with:
+          name: raised_meta
+          path: .
+
+      - name: unstash manifest
+        uses: actions/download-artifact@v3
+        with:
+          name: manifest
+          path: .
+
+      - name: unstash robot_jsons_${{ matrix.distro }}
+        uses: actions/download-artifact@v3
+        with:
+          name: robot_jsons_${{ matrix.distro }}
+          path: .
+
+
+      - name: Install terraform
+        shell: bash
+        run: |
+          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
+          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+          sudo apt update && sudo apt install terraform -y
+  
+      - name: Setup terraform proxmox provisioner
+        id: provision_infra_setup
+        shell: bash
+        run: |
+          provision_infra_dir=provision_scripts
+          provision_infra_version=0.0.1-38
+          provision_infra_repo_name=devops-tf-proxmox-fleet
+
+          rm -rf $provision_infra_dir
+          export PATH="$HOME/.local/bin:$PATH"
+          integration-pipeline fetch_by_tag --repo $provision_infra_repo_name --version $provision_infra_version --gh_api_user $GITHUB_API_USR --gh_api_pwd ${{ secrets.auto_commit_pwd }} --target_dir $provision_infra_dir
+          ls -la $provision_infra_dir
+          echo "target_dir=${provision_infra_dir}/hosts/generic/" >> $GITHUB_OUTPUT
+
+      - name: Define Instance names
+        id: infra_names
+        shell: bash
+        run: |
+          branch=$(echo ${GITHUB_REF#refs/heads/} | sed "s;\.;-;g" )
+
+          local_manager_prefix="ip-hgf-$branch-manager"
+          local_worker_prefix="ip-$branch-worker"
+          echo "$local_manager_prefix"
+          echo "$local_worker_prefix"
+
+          echo "manager_prefix=${local_manager_prefix}" >> $GITHUB_OUTPUT
+          echo "worker_prefix=${local_worker_prefix}" >> $GITHUB_OUTPUT
+
+      - name: Provision remote vms (Proxmox)
+        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
+        shell: bash
+        run: |
+          terraform init -backend-config="key=hel-fleet-${{ steps.infra_names.outputs.manager_prefix }}.tfstate"
+          terraform plan
+          terraform apply -auto-approve
+        env:
+          TF_VAR_number_agents: ${{ inputs.multi_vm_fleet_number_members }}
+          TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
+          TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
+          TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
+          TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
+          TF_VAR_ip_list: ${{ inputs.multi_vm_fleet_ips }}
+          TF_VAR_proxmox_host: "hel"
+          TF_VAR_vm_gateway: "172.22.0.1"
+          TF_VAR_ip_mask: 24
+          TF_VAR_bios: "seabios"
+          TF_VAR_pool: "IP-Temp-VMs"
+          TF_VAR_tags: "ip-fleet"
+
+          TF_VAR_fleet_hosts_user: "devops"
+          TF_VAR_template_name: "ubuntu-2004-cloudinit-template2"
+          TF_VAR_fleet_manager_name: ${{ steps.infra_names.outputs.manager_prefix }}
+          TF_VAR_fleet_manager_memory: 8192
+          TF_VAR_template_name_no_gpu: "ubuntu-2004-cloudinit-template2"
+          TF_VAR_fleet_worker_name_prefix: ${{ steps.infra_names.outputs.worker_prefix }}
+          TF_VAR_fleet_worker_memory: 8192
+
+      - name: Prepare Devops provisioning slack message
+        if: always()
+        id: pre_slack_infra
+        run: |
+          MESSAGE_ERR=":x: CI: ${GITHUB_REPOSITORY}, (${GITHUB_REF#refs/heads/}), build: $(cat product.version) is being impacted by an infrastructural issue. \
+          Provisioning of fleet infrastructure failed. Please take a look! \
+          Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+          echo "msg_error=${MESSAGE_ERR}" >> $GITHUB_OUTPUT
+
+      - name: Slack message failure
+        if: failure()
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          channel-id: "G0102LEV1CL"
+          slack-message: ${{ steps.pre_slack_infra.outputs.msg_error }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}
+
+      - name: Wait for machines getting up
+        id: wait_for_machines
+        shell: bash
+        run: |
+          function ensure_agent_up(){
+            vm_ip=$1
+            i="0"
+            max=15
+            success=1
+            while [ $success -ne 0 ]
+            do
+            echo "Checking if $vm_ip is reachable ($i/$max)"
+            ping -c1 $vm_ip &>/dev/null
+            success=$?
+
+            if [ $i -lt $max ]
+            then
+              i=$[$i+1]
+            else
+              echo "Timeout waiting for $vm_ip"
+              exit 2
+            fi
+
+            sleep 2
+            done
+
+          }
+          echo "${{ secrets.ssh_pem_fleet_aws_vm }}" > ~/.ssh/aws_slave.pem
+          sudo chmod 600 ~/.ssh/aws_slave.pem
+
+          stripped_ips=$(echo ${{ inputs.multi_vm_fleet_ips }} | sed "s;\[;;g" | sed "s;];;g" | sed "s; ;;g")
+          touch ~/.ssh/known_hosts
+          sudo chmod 600 ~/.ssh/known_hosts
+          IFS=',' read -r -a stripped_ips_arr <<< $stripped_ips
+          manager_ip=${stripped_ips_arr[0]}
+          echo $manager_ip
+          echo "manager_ip=${manager_ip}" >> $GITHUB_OUTPUT
+          echo "manager_ssh_conn_string=devops@${manager_ip}" >> $GITHUB_OUTPUT
+          for ip in "${stripped_ips_arr[@]}"
+          do
+            ensure_agent_up $ip
+            ssh-keygen -f ~/.ssh/known_hosts -R $ip
+            ssh-keyscan -H $ip >> ~/.ssh/known_hosts
+          done
+
+      - name: Docker load manager spawner (Remote)
+        shell: bash
+        run: |
+          ssh_conn_string=${{ steps.wait_for_machines.outputs.manager_ssh_conn_string }}
+          ssh $ssh_conn_string -i ~/.ssh/aws_slave.pem -o StrictHostKeyChecking=no '
+            sudo cp /etc/hosts /etc/hosts.bak
+            echo '172.22.0.106 registry.hel.mov.ai' | sudo tee -a /etc/hosts
+            docker login ${{ env.REGISTRY }} -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }}
+            docker login ${{ env.PUSH_REGISTRY }} -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }}
+            docker login ${{ env.MID_REGISTRY }} -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }}
+
+            docker pull "${{ env.MID_REGISTRY }}/ci/${{ inputs.product_name }}-${{ matrix.distro }}:${{ needs.Build-Spawner.outputs.raised_version }}"
+            docker tag "${{ env.MID_REGISTRY }}/ci/${{ inputs.product_name }}-${{ matrix.distro }}:${{ needs.Build-Spawner.outputs.raised_version }}" "${{ env.REGISTRY }}/qa/${{ inputs.product_name }}-${{ matrix.distro }}:${{ needs.Build-Spawner.outputs.raised_version }}"
+            docker tag "${{ env.MID_REGISTRY }}/ci/${{ inputs.product_name }}-${{ matrix.distro }}:${{ needs.Build-Spawner.outputs.raised_version }}" "${{ env.PUSH_REGISTRY }}/qa/${{ inputs.product_name }}-${{ matrix.distro }}:${{ needs.Build-Spawner.outputs.raised_version }}"
+          '
+
+      - name: Setup ansible installation
+        id: ansible_install_setup
+        shell: bash
+        run: |
+          install_key=ansible_deploy
+
+          rm -f /tmp/target_dir.txt /tmp/version.txt /tmp/repo_name.txt
+          export PATH="$HOME/.local/bin:$PATH"
+          integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.installation.$install_key.target_dir --output_file /tmp/target_dir.txt
+          integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.installation.$install_key.version --output_file /tmp/version.txt
+          integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.installation.$install_key.name --output_file /tmp/repo_name.txt
+          install_infra_dir=$(cat /tmp/target_dir.txt)
+          install_infra_version=$(cat /tmp/version.txt)
+          install_infra_repo_name=$(cat /tmp/repo_name.txt)
+
+          rm -rf $install_infra_repo_name
+          integration-pipeline fetch_by_tag --repo $install_infra_repo_name --version $install_infra_version --gh_api_user $GITHUB_API_USR --gh_api_pwd ${{ secrets.auto_commit_pwd }} --target_dir $install_infra_dir
+          ls -la $install_infra_dir
+          echo "target_dir=${install_infra_dir}" >> $GITHUB_OUTPUT
+  
+      - name: Ansible install platform
+        id: ansible_install_platform
+        working-directory: ${{ steps.ansible_install_setup.outputs.target_dir }}
+        shell: bash
+        run: |
+          
+          cp ../${{ steps.provision_infra_setup.outputs.target_dir }}/hosts hosts
+          cp -r ../*.json ./templates/fleet/
+          cp ../product-manifest.yaml ./templates/fleet/product-manifest.yaml
+          cat hosts
+          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do echo Waiting for other software managers to finish... ; sleep 5;done
+          
+          sudo apt install -y python3.9 python3.9-venv
+          python3.9 -m venv ansible-venv
+          source ansible-venv/bin/activate
+          echo "./fleet_install.sh setup --product-artifacts ./templates/fleet/ -i hosts -m install" >> INSTALL.TXT
+          ./fleet_install.sh setup --product-artifacts ./templates/fleet/ -i hosts -m install
+        env:
+          GITHUB_USER: ${{ env.GITHUB_API_USR }}
+          GITHUB_TOKEN: ${{ secrets.auto_commit_pwd }}
+
+      - name: Compress install
+        shell: bash
+        run: |
+          tar -czf fleet_install.tar.gz -C ${{ steps.ansible_install_setup.outputs.target_dir }} .
+
+      - name: Stash Install scripts
+        uses: actions/upload-artifact@v3
+        with:
+          name: install_archive
+          path: fleet_install.tar.gz
+          retention-days: 3
+  
+      - name: Collect Installed components
+        if: always()
+        shell: bash
+        run: |
+            echo "PLACEHOLDER"
+  
+      - name: Get current job id
+        if: always()
+        shell: bash
+        id: job_info
+        run: |
+          sudo apt install jq -y
+          job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | .[0].id')
+          job_html_url=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs | jq -r '.jobs | map(select(.name | contains("${{ github.job }}"))) | .[0].html_url')
+          echo "$job_id"
+          echo "$job_html_url"
+          echo "job_url=$job_html_url" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.gh_token }}
+
+      - name: Prepare slack variables
+        if: always()
+        id: pre_slack_result
+        run: |
+          MESSAGE=":white_check_mark: ${{ github.job }} (Attempt: #${{ github.run_attempt }}) job passed"
+          MESSAGE_ERR=":x: ${{ github.job }} (Attempt: #${{ github.run_attempt }}) job failed"
+          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
+          echo "msg_error=${MESSAGE_ERR}\n  Details: ${{ steps.job_info.outputs.job_url }}" >> $GITHUB_OUTPUT
+
+      - name: Slack message success
+        uses: archive/github-actions-slack@master
+        with:
+          slack-function: send-message
+          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
+          slack-channel: ${{ env.SLACK_CHANNEL }}
+          slack-text: ${{ steps.pre_slack_result.outputs.msg }}
+          slack-optional-thread_ts: ${{ needs.Build-Spawner.outputs.slack_thread_id }}
+
+      - name: Slack message failure
+        uses: archive/github-actions-slack@master
+        if: failure()
+        with:
+          slack-function: send-message
+          slack-bot-user-oauth-access-token: ${{ secrets.slack_token_id }}
+          slack-channel: ${{ env.SLACK_CHANNEL }}
+          slack-text: ${{ steps.pre_slack_result.outputs.msg_error }}
+          slack-optional-thread_ts: ${{ needs.Build-Spawner.outputs.slack_thread_id }}
+
+      - name: Teardown remote vms (Proxmox)
+        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
+        if: ${{ ( !inputs.debug_fleet_keep_alive && success() ) || cancelled() || ( !inputs.debug_fleet_keep_alive && failure() ) }}
+        shell: bash
+        run: terraform destroy -auto-approve
+        env:
+          TF_VAR_number_agents: ${{ inputs.multi_vm_fleet_number_members }}
+          TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
+          TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
+          TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
+          TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
+          TF_VAR_ip_list: ${{ inputs.multi_vm_fleet_ips }}
+  
+      - name: Stash project metadata
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: project_metadata
+          path: metadata_artifact/*
+          retention-days: 3
+
+      - name: Stash deploy_artifacts_noetic
+        uses: actions/upload-artifact@v3
+        with:
+          name: deploy_artifacts_noetic
+          path: artifacts/*
+          retention-days: 5
+
+      - name: Remove robots
+        if: always()
+        continue-on-error: true
+        shell: bash
+        run: |
+          for robot in $(movai-cli robots list); do
+            movai-cli robots stop $robot
+            sleep 5
+            movai-cli robots remove $robot
+          done || true
+
+      - name: Docker cleanups
+        if: always()
+        continue-on-error: true
+        shell: bash
+        run: |
+          docker system prune -f
+          docker image prune --all -f
+        
 
   publish:
-    needs: [Install-Robot, Install-Heterogeneos-Fleet, Install-Simulator-Robot]
+    needs: [Install-Robot, Install-Heterogeneos-Fleet-Single-VM,Install-Heterogeneos-Fleet-Multi-VM, Install-Simulator-Robot]
     runs-on: integration-pipeline
     container:
       image: registry.aws.cloud.mov.ai/qa/py-buildserver:v2.0.1
