Add movai service logs in v2 (#162)
* added movai-service logs

* deleted --no-pager

* added movai-service logs saving to all relevant files

* Save logs for installation and simulator tests too

---------

Co-authored-by: Violeta Leite <violeta.leite@mov.ai>

diff --git a/.github/workflows/integration-build-platform.yml b/.github/workflows/integration-build-platform.yml
--- a/.github/workflows/integration-build-platform.yml
+++ b/.github/workflows/integration-build-platform.yml
@@ -334,6 +334,9 @@ jobs:
           CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
           docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
 
+          # movai-service
+          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
+
       - name: Stash QA artifacts
         if: always()
         shell: bash
@@ -522,6 +525,49 @@ jobs:
             mobtest proj /opt/ros/noetic/share/
             '
 
+      - name: Save docker container logs
+        if: always()
+        working-directory: ${{ steps.install_tests_setup.outputs.target_dir }}
+        shell: bash
+        run: |
+          # for sanity
+          docker ps -a
+
+          # backend
+          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^backend-.*")
+          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # spawner
+          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
+          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # movai-service
+          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
+
+      - name: Stash QA artifacts
+        if: always()
+        shell: bash
+        env:
+          INSTALL_DIR: ${{ steps.install_tests_setup.outputs.target_dir }}
+        run: |
+          # cleanup
+          rm -rf qa_artifacts
+
+          # tests artifacts
+          # *.log might not exist if the test fails early
+          mkdir -p qa_artifacts
+          cp -r "${INSTALL_DIR}"/*.log ./qa_artifacts || true
+          cp -r "${INSTALL_DIR}"/results/*.log ./qa_artifacts || true
+          cp -r "${INSTALL_DIR}"/results/*.zip ./qa_artifacts || true
+          cp -r "${INSTALL_DIR}"/results/test_report_*.html ./qa_artifacts || true
+
+      - name: Stash QA artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: qa_artifacts_install_tests
+          path: qa_artifacts/*
+
       - name: Collect Installed components
         shell: bash
         run: |
@@ -574,20 +620,6 @@ jobs:
         run: |
           # cleanup
           rm -rf qa_artifacts
-
-          # tests artifacts
-          # *.log and *.zip might not exist if the test fails early
-          mkdir -p qa_artifacts
-          cp -r "${INSTALL_DIR}"/results/*.log ./qa_artifacts || true
-          cp -r "${INSTALL_DIR}"/results/*.zip ./qa_artifacts || true
-          cp -r "${INSTALL_DIR}"/results/test_report_*.html ./qa_artifacts || true
-
-      - name: Stash QA artifacts
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: qa_artifacts_install_tests
-          path: qa_artifacts/*
 
       - name: Remove robots
         if: always()
@@ -738,6 +770,9 @@ jobs:
           # spawner
           CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
           docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # movai-service
+          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
 
       - name: Stash QA artifacts
         if: always()
@@ -932,6 +967,9 @@ jobs:
           # spawner
           CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
           docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # movai-service
+          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
 
       - name: Stash QA artifacts
         if: always()
@@ -1498,6 +1536,46 @@ jobs:
             --tb=short
 
           deactivate
+
+      - name: Save docker container logs
+        if: always()
+        working-directory: ${{ steps.sim_flow_tests_setup.outputs.target_dir }}
+        shell: bash
+        run: |
+          # for sanity
+          docker ps -a
+
+          # backend
+          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^backend-.*")
+          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # spawner
+          CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
+          docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+          # movai-service
+          journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
+
+      - name: Stash QA artifacts
+        if: always()
+        shell: bash
+        env:
+          SIM_DIR: ${{ steps.sim_flow_tests_setup.outputs.target_dir }}
+        run: |
+          # cleanup
+          rm -rf qa_artifacts
+
+          # tests artifacts
+          # *.log might not exist if the test fails early
+          mkdir -p qa_artifacts
+          cp -r "${SIM_DIR}"/*.log ./qa_artifacts || true
+
+      - name: Stash QA artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: qa_artifacts_simulator_tests
+          path: qa_artifacts/*
 
       - name: Collect Installed components
         shell: bash
