Update teardown attempts with if (#276)
* tear down attempts

* update attempts to teardown

---------

Co-authored-by: Alex Fernandes <84147256+AlexFernandes-MOVAI@users.noreply.github.com>

diff --git a/.github/workflows/integration-build-platform.yml b/.github/workflows/integration-build-platform.yml
--- a/.github/workflows/integration-build-platform.yml
+++ b/.github/workflows/integration-build-platform.yml
@@ -1534,10 +1534,17 @@ jobs:
           count=0
           while [ $count -lt $attempts ]; do
             var_file_arg='-var-file=../${{ steps.infra_env_configs_setup.outputs.target_dir }}/hel/hel_fleet_test.tfvars'
-            terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars && break
-            ((count++))
-            echo "Retrying Terraform destroy (attempt $count)..."
-            sleep 10  # Add a delay before retrying (optional)
+            terraform destroy -auto-approve $var_file_arg -var-file=input.tfvars 
+            exit_status=$?
+            if [ $exit_status -eq 0 ]; then
+              break
+            elif [ $exit_status -eq 1 ]; then
+              ((count++))
+              echo "Retrying Terraform destroy (attempt $count)..."
+            else
+                  echo "Terraform destroy failed with exit status ${exit_status:-unknown}. Exiting..."
+                  exit ${exit_status:-1}
+            fi
           done
 
   Build-Simulator:
