add tests

diff --git a/.github/workflows/integration-build-product.yml b/.github/workflows/integration-build-product.yml
--- a/.github/workflows/integration-build-product.yml
+++ b/.github/workflows/integration-build-product.yml
@@ -394,6 +394,14 @@ jobs:
 
           echo "config_pre_exists=$CONFIG_FILE_EXISTS" >> $GITHUB_OUTPUT
 
+      - name: Remote - Agent info
+        id: agent_info
+        run: |
+          ssh robot '
+            ip=$(hostname -I | awk "{print $1}")
+            echo $ip
+          '
+
       - name: Remote - Login to Private Registry
         shell: bash
         run: ssh robot "docker login ${{ env.REGISTRY }} -u ${{ secrets.registry_user }} -p ${{ secrets.registry_password }}"
@@ -452,6 +460,50 @@ jobs:
         run: |
           ssh robot 'cd ${{ env.REMOTE_WORKSPACE }}; ls -la'
 
+      - name: Remote - Setup QA Simulation tests
+        shell: bash
+        id: simulator_tests_setup
+        run: |
+          ssh robot '
+            cd ${{ env.REMOTE_WORKSPACE }}
+
+            qa_key=simulator_tests
+
+            rm -f /tmp/target_dir.txt /tmp/version.txt /tmp/repo_name.txt /tmp/test_set.txt
+            export PATH="$HOME/.local/bin:$PATH"
+  
+            integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.qa.$qa_key.target_dir --output_file /tmp/target_dir.txt
+            integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.qa.$qa_key.version --output_file /tmp/version.txt
+            integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.qa.$qa_key.name --output_file /tmp/repo_name.txt
+            integration-pipeline get_yml_value --file product-manifest.yaml --key product_components.qa.$qa_key.test_set --output_file /tmp/test_set.txt
+  
+            tests_dir=$(cat /tmp/target_dir.txt)
+            tests_version=$(cat /tmp/version.txt)
+            tests_repo_name=$(cat /tmp/repo_name.txt)
+            test_set=$(cat /tmp/test_set.txt)
+
+            rm -rf $tests_repo_name
+            integration-pipeline fetch_by_tag --repo $tests_repo_name --version $tests_version --gh_api_user $GITHUB_API_USR --gh_api_pwd ${{ secrets.auto_commit_pwd }} --target_dir $tests_dir
+            ls -la $tests_dir
+
+            # setup venv in a step that is always executed
+            pushd "${tests_dir}"
+            rm -rf venv
+            python3 -m venv venv
+            . venv/bin/activate
+            python3 -m pip install --upgrade pip
+            pip install -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple --extra-index-url https://pypi.org/simple -r requirements.txt
+            deactivate
+            popd
+
+          '
+          rm -f /tmp/target_dir.txt /tmp/version.txt /tmp/repo_name.txt /tmp/test_set.txt
+          scp -r robot:/tmp/*.txt /tmp/
+
+          echo "target_dir=$(cat /tmp/target_dir.txt)" >> $GITHUB_OUTPUT
+          echo "version=$(cat /tmp/version.txt)" >> $GITHUB_OUTPUT
+          echo "test_set=$(cat /tmp/test_set.txt)" >> $GITHUB_OUTPUT
+
       - name: Remote - Install
         id: install
         shell: bash
@@ -487,13 +539,100 @@ jobs:
             movai-cli robots user "$robot" "$MOVAI_USER" "$MOVAI_PWD"
           done
 
-          echo "movai_user=${MOVAI_USER}" >> $GITHUB_OUTPUT
-          echo "movai_pwd=${MOVAI_PWD}" >> $GITHUB_OUTPUT
           execution_status=$?
           exit $execution_status
           rm movai_service_version
           '
+          echo "movai_user=ci" >> $GITHUB_OUTPUT
+          echo "movai_pwd=4Iva6UHAQq9DGITj" >> $GITHUB_OUTPUT
 
+      - name: Remote - Simulation Tests
+        shell: bash
+        run: |
+          ssh robot '
+
+            cd ${{ env.REMOTE_WORKSPACE }}
+
+            # install test dependencies on host
+            sudo apt install -y --allow-downgrades python3-rosnode python3-rosparam python3-rostopic
+            export PYTHONPATH="${PYTHONPATH}:/usr/lib/python3/dist-packages"
+
+            # install test dependencies on spawner
+            ## get spawner container name
+            CONTAINER_ID=$(docker ps --format '{{.Names}}' --filter "name=^spawner-.*")
+            ## get apt dependencies
+            #APT_DEPS=$(cat apt-requirements.txt | tr "\n" " ")
+            ## install
+            # docker exec -t "${CONTAINER_ID}" bash -c "
+            #   sudo apt update
+            #   sudo apt install -y ${APT_DEPS}
+            # "
+
+            # run tests
+            . venv/bin/activate
+
+            pytest \
+              -s \
+              -ra \
+              --movai-user ${{ steps.install.outputs.movai_user }} \
+              --movai-pw ${{ steps.install.outputs.movai_pwd }} \
+              -m '${{ steps.simulator_tests_setup.outputs.test_set }}' \
+              --tb=short
+
+            deactivate
+          '
+
+      - name: Remote - Save docker container logs
+        if: always()
+        shell: bash
+        run: |
+          ssh robot '
+
+            cd ${{ env.REMOTE_WORKSPACE }}/${{ steps.simulator_tests_setup.outputs.target_dir }}
+
+            # for sanity
+            docker ps -a
+
+            # backend
+            CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^backend-.*")
+            docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+            # spawner
+            CONTAINER_ID=$(docker ps -a --format '{{.Names}}' --filter "name=^spawner-.*")
+            docker logs "${CONTAINER_ID}" &> "${CONTAINER_ID}.log"
+
+            # movai-service
+            journalctl -u movai-service --since '1hour ago' &> "movai-service.log"
+            
+            # spawner (mobros firmware)
+            journalctl -u movai-service -t mobros --since '1hour ago' &> spawner-firmware.log || true
+          '
+
+      - name: Remote - Stash QA artifacts
+        if: always()
+        shell: bash
+        run: |
+          ssh reobot '
+            cd ${{ env.REMOTE_WORKSPACE }}
+
+            # cleanup
+            rm -rf qa_artifacts
+
+            # tests artifacts
+            # *.log might not exist if the test fails early
+            mkdir -p qa_artifacts
+            cp -r "${{ steps.simulator_tests_setup.outputs.target_dir }}"/*.log ./qa_artifacts || true
+          '
+          scp -r robot:${{ env.REMOTE_WORKSPACE }}/qa_artifacts .
+
+
+      - name: Stash QA artifacts
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: qa_artifacts_simulator_tests
+          path: qa_artifacts/*
+  
       - name: Teardown ssh setup
         shell: bash
         run: |
@@ -502,3 +641,16 @@ jobs:
             rm ~/.ssh/config
             mv ~/.ssh/config.bak ~/.ssh/config
           fi
+
+      # - name: Teardown remote vms (Proxmox)
+      #   working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
+      #   if: ${{ success() || cancelled() || ( !inputs.debug_fleet_keep_alive && failure() ) }}
+      #   shell: bash
+      #   run: terraform destroy -auto-approve
+      #   env:
+      #     TF_VAR_number_agents: ${{ inputs.fleet_number_members }}
+      #     TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
+      #     TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
+      #     TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
+      #     TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
+      #     TF_VAR_ip_list: ${{ inputs.fleet_ips }}
