add step to test nvidia

diff --git a/.github/workflows/integration-build-product.yml b/.github/workflows/integration-build-product.yml
--- a/.github/workflows/integration-build-product.yml
+++ b/.github/workflows/integration-build-product.yml
@@ -1361,7 +1361,7 @@ jobs:
             set -e
             cloud-init status --wait; rm -rf ./${{ env.REMOTE_WORKSPACE_PATH }}; mkdir -p ./${{ env.REMOTE_WORKSPACE_PATH }}
             export DESIRED_DOCKER_VERSION="${{ env.DESIRED_DOCKER_VERSION }}"
-            wget -qO - https://movai-scripts.s3.amazonaws.com/docker_hold.sh | bash 
+            wget -qO - https://movai-scripts.s3.amazonaws.com/docker_hold.sh | bash
           '
 
       - name: Prepare Devops provisioning slack message
@@ -1391,6 +1391,30 @@ jobs:
             ip=$(hostname -I | cut -d " " -f1)
             echo $ip
           '
+
+      - name: Remote - Detect Nvidia mismatch
+        if: ${{ inputs.with_simulation_tests }}
+        shell: bash
+        id: nvidia_check
+        run: |
+          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
+            set -e
+            container_id=$(docker run --gpus=all --rm nvcr.io/nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi 2>&1)
+            if [[ $? -ne 0 ]]; then
+              exit 1
+            fi
+          '
+          echo "msg_error=Nvidia container error detected.\
+          Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
+
+      - name: Slack message failure
+        if: ${{ inputs.with_simulation_tests  && failure() && github.event_name != 'pull_request' }}
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          channel-id: "G0102LEV1CL"
+          slack-message: ${{ steps.nvidia_check.outputs.msg_error }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.slack_token_id }}
 
       - name: Remote - Login to ${{ env.MID_REGISTRY }} Registry
         if: ${{ inputs.with_simulation_tests }}
@@ -1655,7 +1679,7 @@ jobs:
             # spawner (mobros firmware)
             journalctl -u movai-service -t mobros --since "1hour ago" &> spawner-firmware.log || true
 
-            # docker logs 
+            # docker logs
             journalctl -u docker --since "1hour ago" &> "docker-service.log"
           '
 
