temp disable teardown of fleet

diff --git a/.github/workflows/integration-build-platform.yml b/.github/workflows/integration-build-platform.yml
--- a/.github/workflows/integration-build-platform.yml
+++ b/.github/workflows/integration-build-platform.yml
@@ -1122,18 +1122,18 @@ jobs:
           export PATH="$HOME/.local/bin:$PATH"
           aws ec2 terminate-instances --instance-ids $(cat aws_artifacts/infra_ids.txt)
 
-      - name: Teardown remote vms (Proxmox)
-        working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
-        if: ${{ success() || cancelled() || ( !inputs.debug_fleet_keep_alive && failure() ) }}
-        shell: bash
-        run: terraform destroy -auto-approve
-        env:
-          TF_VAR_number_agents: ${{ inputs.fleet_number_members }}
-          TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
-          TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
-          TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
-          TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
-          TF_VAR_ip_list: ${{ inputs.fleet_ips }}
+      # - name: Teardown remote vms (Proxmox)
+      #   working-directory: ${{ steps.provision_infra_setup.outputs.target_dir }}
+      #   if: ${{ success() || cancelled() || ( !inputs.debug_fleet_keep_alive && failure() ) }}
+      #   shell: bash
+      #   run: terraform destroy -auto-approve
+      #   env:
+      #     TF_VAR_number_agents: ${{ inputs.fleet_number_members }}
+      #     TF_VAR_proxmox_api_url: "https://hel.mov.ai:8006/api2/json"
+      #     TF_VAR_proxmox_api_token_id: ${{ secrets.proxmox_api_token_id }}
+      #     TF_VAR_proxmox_api_token_secret: ${{ secrets.proxmox_api_token_secret }}
+      #     TF_VAR_provision_ssh_pem: ${{ secrets.ssh_pem_fleet_aws_vm }}
+      #     TF_VAR_ip_list: ${{ inputs.fleet_ips }}
 
   Build-Simulator:
     needs: [Validate-boostrap-configs]
