Revert "Lint early so no stash is needed"
This reverts commit c563a6610d4168f14947e0f185b146588950e054.

diff --git a/.github/workflows/npm-workflow.yml b/.github/workflows/npm-workflow.yml
--- a/.github/workflows/npm-workflow.yml
+++ b/.github/workflows/npm-workflow.yml
@@ -99,33 +99,12 @@ jobs:
       env:
         npm_token: ${{ secrets.npm_token }}
 
-    - name: Global git config
+    - name: Raise App version
       run: |
         git config --global --add safe.directory $(pwd)
         git config --global user.name '${{ secrets.auto_commit_user }}'
         git config --global user.email '${{ secrets.auto_commit_mail }}'
         git config --global user.password ${{ secrets.auto_commit_pwd }}
-
-    - name: Run lint-staged
-      if: ${{ inputs.run_lint_staged == 'true' }}
-      run: |
-        echo "The following files were changed from origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} and will be validated:"
-        git --no-pager diff "origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}" --name-only
-        echo ""
-
-        npx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
-        echo ""
-
-        # explicitly check for changes and fail if there are any
-        if ! git diff --quiet HEAD; then
-          echo ""
-          echo "ERROR, the following files have changed:"
-          git diff --name-only HEAD
-          exit 1
-        fi
-
-    - name: Raise App version
-      run: |
         ${{ inputs.pm }} version prerelease --no-git-tag-version
 
     - name: Install dependencies
@@ -144,6 +123,31 @@ jobs:
     - name: Check NPM log on failure
       if: ${{ failure() }}
       run: cat /github/home/.npm/_logs/*.log
+
+    - name: Run lint-staged
+      if: ${{ inputs.run_lint_staged == 'true' }}
+      run: |
+        # stash changes done by bumping version
+        git stash
+        echo ""
+
+        echo "The following files were changed from origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} and will be validated:"
+        git --no-pager diff "origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}" --name-only
+        echo ""
+
+        npx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
+        echo ""
+
+        # explicitly check for changes and fail if there are any
+        if ! git diff --quiet HEAD; then
+          echo ""
+          echo "ERROR, the following files have changed:"
+          git diff --name-only HEAD
+          exit 1
+        fi
+
+        # unstash changes done by bumping version
+        git stash apply
 
     - name: Run tests
       if: ${{ inputs.run_tests == 'true' }}
