add deploy

diff --git a/.github/workflows/offline-install-workflow-iso.yml b/.github/workflows/offline-install-workflow-iso.yml
--- a/.github/workflows/offline-install-workflow-iso.yml
+++ b/.github/workflows/offline-install-workflow-iso.yml
@@ -20,6 +20,16 @@ on:
       PRODUCT_VERSION:
         type: string
         required: true
+      deploy:
+        type: string
+        required: true
+      release:
+        type: string
+        required: true
+      slack_channel:
+        required: false
+        type: string
+        default: "C05UYMX2U0K"
     secrets:
       auto_commit_user:
         required: true
@@ -35,8 +45,16 @@ on:
         required: true
       nexus_publisher_password:
         required: true
+env:
+  RUN_STAGING_DIR: "/home/devops/iso-ci/staging/${{ github.repository }}/${{ github.run_id}}/"
+  PROXMOX_NFS_SERVER_PATH: "/media/nas-mary/template/iso/baremetal"
+  PROXMOX_NFS_SERVER_URL: "https://hel.mov.ai:8006/#v1:0:=storage%2Fhel%2Fnas-mary:4:5:=contentIso:::::"
+
 jobs:
-  Validate-features:
+  Build:
+    outputs:
+      raised_version: ${{ steps.raise.outputs.raised_version }}
+      file_name: ${{ steps.prepare_deploy.outputs.file_name }}
     runs-on: packer-runner
     steps:
       - uses: rtCamp/action-cleanup@master
@@ -48,10 +66,23 @@ jobs:
           echo "public ip: $(curl ipinfo.io/ip)"
           echo "private ip: $(hostname -I | awk '{print $1}')"
 
-      # - name: Lint with shellcheck
-      #   uses: azohra/shell-linter@latest
-      #   with:
-      #     path: ./*.bash
+      - name: Lint with shellcheck
+        uses: azohra/shell-linter@latest
+        with:
+          path: ./*.bash
+
+      - name: Raise Version
+        id: raise
+        shell: bash
+        run: |
+          COMP_VERSION=$(cat version)
+          main_version=${COMP_VERSION%-*}
+          build_id="${COMP_VERSION#*-}"
+          raised_buildid=$(($build_id+1))
+          RAISED_COMP_VERSION="$main_version-$raised_buildid"
+          echo $RAISED_COMP_VERSION>version
+          echo $RAISED_COMP_VERSION
+          echo "raised_version=$RAISED_COMP_VERSION" >> $GITHUB_OUTPUT
 
       - name: Create config file
         run: |
@@ -87,7 +118,20 @@ jobs:
         run: |
           mv offline_install_artifacts/* .
           ./mkisofs-movai-autoinstall.bash config.cfg
+
     
+      - name: Prepare for deployment
+        if: ${{ inputs.deploy == 'true' && inputs.release == 'false' }}
+        id: prepare_deploy
+        run: |
+          generated_file_name=${{ inputs.PRODUCT_NAME }}_${{ steps.raise.outputs.raised_version }}_offline_install.iso
+          for file in $(find $RUN_STAGING_DIR -name "*custom*.iso"); do
+            file_dir=$(dirname $file)
+            mv $file "$file_dir/$generated_file_name"
+          done
+          echo "file_name=$generated_file_name" >> $GITHUB_OUTPUT
+
+
       - name: Clean up
         if: always()
         run: |
@@ -95,4 +139,55 @@ jobs:
           docker rmi -f $(docker images -q) || true
 
 
-    
+  Deploy-Images:
+    runs-on: packer-runner
+    needs: [ Build ]
+    if: ${{ inputs.deploy == 'true' && inputs.release == 'false' }}
+    steps:
+      - name: Test NFS server
+        run: |
+          if [ ! -d "$PROXMOX_NFS_SERVER_PATH" ]; then
+            echo "ERROR: NFS server path $PROXMOX_NFS_SERVER_PATH does not exist."
+            exit 1
+          fi
+
+      - name: Deploy images to NFS server
+        run: |
+          sudo mkdir -p $PROXMOX_NFS_SERVER_PATH/
+
+          sudo rsync --progress -z $RUN_STAGING_DIR/${{ needs.Build.outputs.file_name }} $PROXMOX_NFS_SERVER_PATH/
+          echo "Image copied to NFS server to $PROXMOX_NFS_SERVER_URL"
+
+      - name: Prepare slack variables
+        if: always()
+        id: pre_slack
+        run: |
+          MESSAGE=":arrow_forward: New pre-version ${{ needs.Build.outputs.raised_version }} of baremetal image available :sunny:"
+          MESSAGE_ERR=":x: Build of pre-version ${{ needs.Build.outputs.raised_version }} is unstable :rain_cloud: Details: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+
+          echo "msg=${MESSAGE}" >> $GITHUB_OUTPUT
+          echo "msg_error=${MESSAGE_ERR}" >> $GITHUB_OUTPUT
+
+      - name: Slack message success
+        uses: slackapi/slack-github-action@v1.25.0
+        with:
+          channel-id: ${{ inputs.slack_channel }}
+          slack-message: ${{ steps.pre_slack.outputs.msg }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_ID }}
+
+      - name: Slack message failure
+        if: failure()
+        uses: slackapi/slack-github-action@v1.25.0
+        with:
+          channel-id: ${{ inputs.slack_channel }}
+          slack-message: ${{ steps.pre_slack.outputs.msg_error }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_ID }}
+
+      - name: Cleanup
+        if: always()
+        shell: bash
+        run: |
+          rm -rf $RUN_STAGING_DIR
+        
