try same push to qa code

diff --git a/.github/workflows/py-deb-workflow.yml b/.github/workflows/py-deb-workflow.yml
--- a/.github/workflows/py-deb-workflow.yml
+++ b/.github/workflows/py-deb-workflow.yml
@@ -452,15 +452,50 @@ jobs:
         repository_url: https://artifacts.cloud.mov.ai/repository/${{ inputs.prod_publish_pypi }}/
 
     - name: Publish to Nexus
+      shell: bash
       run: |
-          NEXUS_REPO="${{ matrix.publish_repo }}"
-          if [ "$NEXUS_REPO" != "ppa-public" ]; then
-            NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
-          else
-            NEXUS_ENDPOINT="artifacts.aws.cloud.mov.ai"
-          fi
-          FILE_LOCATION=$(find artifacts/*.deb)
-          find artifacts -type f -name '*.deb' -exec curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-          -H "Content-Type: multipart/form-data" \
-          --data-binary "@{}" \
-          "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/" \;
+            NEXUS_REPO="${{ matrix.publish_repo }}"
+            if [ "$NEXUS_REPO" != "ppa-public" ]; then
+              NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
+            else
+              NEXUS_ENDPOINT="artifacts.aws.cloud.mov.ai"
+            fi
+
+            for file in artifacts/*.deb
+            do
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+              -H "Content-Type: multipart/form-data" \
+              --data-binary "@$file" \
+              -w '%{http_code}' \
+              "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+
+              #retry
+              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+                echo "Failed upload with $RETURN_CODE. Retrying"
+
+                RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                  -H "Content-Type: multipart/form-data" \
+                  --data-binary "@$file" \
+                  -w '%{http_code}' \
+                  "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+              fi
+
+              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+                echo "Failed upload with $RETURN_CODE. Exiting"
+                exit 1
+              fi
+
+            done
+    # - name: Publish to Nexus
+    #   run: |
+    #       NEXUS_REPO="${{ matrix.publish_repo }}"
+    #       if [ "$NEXUS_REPO" != "ppa-public" ]; then
+    #         NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
+    #       else
+    #         NEXUS_ENDPOINT="artifacts.aws.cloud.mov.ai"
+    #       fi
+    #       FILE_LOCATION=$(find artifacts/*.deb)
+    #       find artifacts -type f -name '*.deb' -exec curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+    #       -H "Content-Type: multipart/form-data" \
+    #       --data-binary "@{}" \
+    #       "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/" \;
