test

diff --git a/.github/workflows/ros-workflow.yml b/.github/workflows/ros-workflow.yml
--- a/.github/workflows/ros-workflow.yml
+++ b/.github/workflows/ros-workflow.yml
@@ -216,11 +216,31 @@ jobs:
           NEXUS_ENDPOINT="artifacts.aws.cloud.mov.ai"
           NEXUS_REPO="ppa-testing"
 
-          find artifacts -type f -name '*.deb' -exec curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-          -H "Content-Type: multipart/form-data" \
-          --data-binary "@{}" \
-          "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/" \;
+          for file in artifacts/*.deb
+          do
+            RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+            -H "Content-Type: multipart/form-data" \
+            --data-binary "@$file" \
+            -w '%{http_code}' \
+            "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
 
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Retrying"
+            
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                -H "Content-Type: multipart/form-data" \
+                --data-binary "@$file" \
+                -w '%{http_code}' \
+                "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+            fi
+
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+            
+          done
 
     - name: Commit raise version
       id: raise
