now with retry and exit code

diff --git a/.github/workflows/ros-workflow-alpha.yml b/.github/workflows/ros-workflow-alpha.yml
--- a/.github/workflows/ros-workflow-alpha.yml
+++ b/.github/workflows/ros-workflow-alpha.yml
@@ -221,6 +221,7 @@ jobs:
       run: |
           NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
           NEXUS_REPO="ppa-dev"
+          
           for file in artifacts/*.deb
           do
             RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
@@ -228,7 +229,23 @@ jobs:
             --data-binary "@$file" \
             -w '%{http_code}' \
             "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
-            echo $RETURN_CODE
+
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Retrying"
+            
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                -H "Content-Type: multipart/form-data" \
+                --data-binary "@$file" \
+                -w '%{http_code}' \
+                "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+            fi
+
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+            
           done
     
     - name: Publish to Nexus ppa-testing
@@ -244,7 +261,23 @@ jobs:
             --data-binary "@$file" \
             -w '%{http_code}' \
             "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
-            echo $RETURN_CODE
+
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Retrying"
+            
+              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                -H "Content-Type: multipart/form-data" \
+                --data-binary "@$file" \
+                -w '%{http_code}' \
+                "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+            fi
+
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
+              echo "Failed upload with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+            
           done
 
     - name: Create Github Release
